name: push-a-commit

on:
  schedule:
    - cron: "37 0 * * *"
  pull_request:

jobs:
  benchmarks:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: make a commit
        run: |
           echo "oops"
