name: push a commit
on:
  schedule:
    - cron: "10 * * * *"
permissions:
  contents: write
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit
        run: |
            git config --global user.name "bot"
            git config --global user.email "no@email.com"
            export BRANCHNAME=empty`date +%s`
            git checkout -b $BRANCHNAME
            date > date.txt
            git commit -am'automated commit'
            git log
       - name: Send a PR
         run: gh pr create -B trigger -H $BRANCHNAME --title 'Merge' --body 'Created by a Github action'
